# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: newtlom/flask
        # tags: v3, latest
        tags: ${{ github.sha }}
        registry: docker.io
        username: newtlom
        password: dckr_pat_ykrd-oqtw6lDax67-KK9iQBBpec
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2      
      with:         
         app-name: 'cdgithubaction37'
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         images: 'newtloim/flask:${{ github.sha }}'
